### PR TITLE
Link stopify locally so callcc can require module without relative path

### PR DESCRIPTION
**Pull request by baxtersa**

### CODE REVIEW

**Comment by arjunguha** [comment]
Have you tried to use Stopify as a Babel plugin (to get callCC)? Babel plugins rely on default exports. This seems to me a mix of a default export (callcc) and normal exports (runtime). Whether or not it works, I don't fully get ES6 modules.

**Comment by baxtersa** [comment]
Good question, I haven't tried. I'll look at it today.

Do you mean programmatically? So try to call `babel.transform` with `Stopify` as a plugin?

**Comment by arjunguha** [comment]
Programmatically, or by putting `Stopify` in a `.babelrc` file, which is what Nicole is doing. If it doesn't work, I'd consider creating a separate Node package that only exports the plugin.

**Comment by baxtersa** [comment]
It still works.

I was able to run `babel --plugin Stopify <file>` and it successfully transformed the code.

**Comment by baxtersa** [comment]
Crap, never mind, not working. Working on fixing it.

**Comment by baxtersa** [comment]
Fixed.

**Pull request merged**
