### PR TITLE
220 (do not merge)

### PR DESCRIPTION
**Pull request by arjunguha**

### CODE REVIEW

**Comment by arjunguha** [comment]
@baxtersa I'd like to know what you think of merging in these commits (after some cleanup). At a high-level, there are two significant changes:

1. The .externals compiler option is gone. Instead, global variables are set as properties of a global object. You can see an example here: https://github.com/plasma-umass/Stopify/pull/397/commits/eeb48eb2c8171f5604c7a420ba12b303441cb1a0#diff-8cc0452b1054416799bec2e2b91e6693R45  I don't know if it affects performance (my guess is no). But, it is a representation change. This approach has two advantages:

   a. The global values in stopified code do not have to also be globals in the host page. In fact, a global to stopify can be an anonymous value.

   b. It enables a REPL-style eval function described below.

2. I have added an evalAsync function that facilitates building a REPL (https://github.com/plasma-umass/Stopify/pull/397/files#diff-61a3406d3603a3db6619606180771c55R36). It is slightly simpler than the previous implementation of eval, because it does not have a program transformation that looks for uses of `eval` and translates them away. However, in combination with the new global object, we can simulate the eval function without a program transformation at all. You can see it in action here: (https://github.com/plasma-umass/Stopify/pull/397/files#diff-00328d0364da3eaf9c29031fe393b681R21). There is one difference. This version of eval does not have local variables in scope, which is something that the full-blown eval could support. I think we can drop this feature. The real use-case for eval is not to simulate JS eval in full detail, but to facilitate building REPLs. How do you feel about dropping the old eval in favor of this new eval? It would allow us to eliminate the eval program transformation and some options.

Summary: (1) is a representation change that may affect your work at IBM. (2) Is an alternative implementation of eval that should not affect your work.

Thoughts?

**Comment by baxtersa** [comment]
Sorry it took a while to look at this.

1. Not polluting the global namespace feels like the right way to go in general.

Is there any reason this has to be a part of `stopify-continuations`? If this can be moved entirely to the `stopify` package, it certainly will not affect my serverless work. I think it belongs with the `Runner` class anyway, but if this is something we want in packages that only use `stopify-continuations` to be able to use, I think I'd advocate for moving the runtime support for the global object transform into `stopify-continuations` as well. Other than that, I like the change.

2. I like this change too. I'm all for imposing restrictions on our `eval` support, as long as the restrictions are easy to understand/documented. Ideally, we can even enforce the restrictions at runtime.

**Comment by arjunguha** [comment]
Are you proposing we keep the `.externals` flag and do `$S.g` in the Stopify?

I see that `$S.g` relies on Stopify's runner. I am in favor of simplifying `stopify-continuations` to the point where it doesn't bother with any kind of wrapping / modularity.

**Comment by baxtersa** [comment]
I'm proposing we do `$S.g` in `stopify`, and still get rid of `.externals`. `stopify-continuations` only uses `.externals` in its `eval` transform, which this PR gets rid of anyway.

In other words, is it possibly to move the `useGlobalObject` transform pass into `stopifyCallCC.ts` in the `stopify` package instead of in `callcc.ts` in the `stopify-continuations` package?

**Comment by arjunguha** [comment]
I'm deleting this branch. Most changes have been merged in. We are now working off:

https://github.com/plasma-umass/Stopify/pull/402

**Pull request closed without merging**
