### PR TITLE
webpack fix

### PR DESCRIPTION
**Pull request by rachitnigam**
This fix is required for webpack to not be pulled in as a dependency when the stopify module is browserified.

### CODE REVIEW

**Comment by arjunguha** [comment]
Two comments:

1. This is in the compiler and not the runtime system. Are you really linking Pyret to the Stopify compiler?

2. Webpack has a way to exclude certain modules from linking. Doesn't browserify have such a feature?

**Comment by rachitnigam** [comment]
1. To run a StoPyret program, I need the runtime. To bootstrap and run the StoPyret compiler (which is a Pyret program too), I need both.

2. We pack indeed allows you to not pull in packages. However the top level import is causing trouble since anytime index is imported, require(“webpack”) is run. As far as I can tell, browserify doesn’t have an easy way of stubbing module. 

However I think this should be fixed Stopify side not pyret side since Stopify is producing the compiler. A potentially neater way of doing this would be webpacking a Stopify compiler bundle which I can look into.

P.S. JavaScript module management sucks.

**Comment by arjunguha** [comment]
How would a Stopify compiler bundle help? Is the idea that it would still have webpack, but would not interfere with Pyret?

**Comment by rachitnigam** [comment]
Yeah, instead of doing `require('Stopify')` I would (somehow) pull in the bundle. The bundle will not have webpack.

However, I don't really like this idea that much since `require('Stopify')` is much more convenient from the point of view of somehow using Stopify.

**Pull request merged**
